<!-- Beginning of Bottom Matter -->
<hr />

<div id="footer" class="bottom append-bottom incr span-24">
<a rel="license" href="http://creativecommons.org/licenses/by/3.0/"><img class="left" alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by/3.0/80x15.png" /></a>This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/">Creative Commons Attribution 3.0 Unported License</a>. <div class="right"><a href="http://www.andrewleifer.com">Andrew Leifer</a> <a href="mailto:leifer@fas.harvard.edu">leifer@fas.harvard.edu</a></div>
</div>



</div>  <!-- container -->
</body>

</html>

