
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
<head>
<title>CoLBeRT: <?php echo $title; ?> </title>
<link rel="stylesheet" href="css/blueprint/screen.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="css/blueprint/print.css" type="text/css" media="print">
<link rel="stylesheet" href="css/colbert.css" type="text/css" media="screen, projection">
<!--[if lt IE 8]>
  <link rel="stylesheet" href="css/blueprint/ie.css" type="text/css" media="screen, projection">
  <![endif]-->

 <!-- Import fancy-type plugin. -->  

<link rel="stylesheet" href="css/blueprint/plugins/fancy-type/screen.css" type="text/css" media="screen, projection" />
</head>

<body>

<div class ="container">

<hr class="space" />
<h1 class="left">CoLBeRT</h1> 
<img src="images/wormInColbert.png" class="left">
<h2 class="alt left "><strong>Co</strong>ntrolling <strong>L</strong>ocomotion and <strong>Be</strong>havior in <strong>R</strong>eal-<strong>T</strong>ime</h2>



<hr />
<h4 class="nav"><a href="/index.php">Home</a></h4>
<h4 class="nav"><a href="/">Images</a></h4>
<h4 class="nav"><a href="/videos.php">Videos</a></h4>
<h4 class="nav"><a href="/">Code</a></h4>
<h4 class="nav"><a href="/">Links</a></h4>
<h4 class="nav"><a href="/">Publications</a></h4>
<h4 class="nav right"><a href="http://www.fas.harvard.edu">Harvard</a></h4>

<h4 class="nav right"><a href="http://worms.physics.harvard.edu/">Samuel Lab</a></h4>
<hr id="bottomheader" />


<hr class="space">

<div id="mainbody" class="span-24 last">

<!------- END OF TOP MATTER -->
